project:
  type: website
  output-dir: "."

website:
  title: "Hannah Olejniczak"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.ipynb
      - text: Blog
        href: blog-listing.qmd
      - text: Homework
        href: hw.qmd
      - text: Python Basics
        href: basic-python-intro.ipynb
      - text: "Python Data Analysis"
        menu: 
          - basic-python-intro.ipynb
          - danl-210-quatro.qmd
    page-footer: 
    center: "Powered with GitHub and Quarto<br>© YOUR NAME, 2023"

format:
  html:
    theme: 
      light: journal
      dark: solar
    mainfont: system-ui; 
    highlight-style: breeze
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    

